# Uso Numpy uso básico de matrices


In [1]:
import numpy as np

definimos una matriz 2x3

In [24]:
A = np.array( [[1,2,3] ,[4,5,6]])
print (A)

[[1 2 3]
 [4 5 6]]


sumar dos matrices ( deben ser del mismo rango )

In [25]:
B = np.array([[1,2,3],[0,1,2]])
C = A+B
print (C)

[[2 4 6]
 [4 6 8]]


multiplicamos un escalar ( es equivalente a un float, con signo ) y una matriz


In [27]:
escalar = -1.2
D = escalar*C
print(D)

[[-2.4 -4.8 -7.2]
 [-4.8 -7.2 -9.6]]


multiplicamos dos matrices de rangos no compatibles 2x2 y 3x2


In [35]:
E = np.array([[2,2],[2,2]])
F = np.array([[1,1],[1,1],[1,1]]) 

# al multiplicar da error al no ser compatibles los rangos
try:
   H = np.matmul(E,F)
except ValueError:
   print ("Los rangos no son compatibles") 



Los rangos no son compatibles


En este caso si hay multiplicación debido a que el rango de las matrices son 2x2 y 2x3, dando lugar al multiplicar una matriz de rango 2x3.


In [30]:
F = np.array([[1,1,1],[1,1,1]])
H = np.matmul(E,F)
print(H)

[[4 4 4]
 [4 4 4]]
